---
title: "Untitled"
output: 
  html_document: 
    theme: journal
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	fig.showtext = TRUE,
	fig.retina = 1,
	dev = "CairoPNG",
	dpi = 150
)
```

```{r}
library(tidyverse)
library(tidycensus)
library(readxl)
library(showtext)
library(camiller)
library(ggmosaic)
library(waffle)
library(sf)
library(RSocrata)

```

```{r}
# font_families_google()
font_add_google("Archivo Narrow", "archivo")
# font_add_google("PT Sans", "ptsans")
showtext_auto()
showtext_opts(dpi = 150)
```

```{r}
xl_path <- "input/waterbury profile data for design.xlsx"
# pal <- c(RColorBrewer::brewer.pal(n = 9, name = "YlGnBu"), "#040e29")
pal <- c("#ffffa3", "#e8f792", "#c6efaf", "#79d2be", "#3abccb", "#1296ca", "#195eb3", "#1e2f99", "#051c5c", "#040e29")
pal4 <- pal[c(4, 5, 7, 10)]
pal5 <- pal[5:9]

pal_qual <- c("#1e2f99", "#7f1c8a", "#af0870", "#c92952", "#d15236", "#ca781f", "#b89b20", "#9cba43")

```

```{r}
towns <- read_excel(xl_path, sheet = 1, skip = 1) %>% pull(1)
sheet_info <- list(
  age_race = list(sheet = 2, range = "A3:F9"),
  proj_pop = list(sheet = 2, range = "A15:G21"),
  industry = list(sheet = 3, range = "A11:F19"),
  resources = list(sheet = 4, range = "A3:D17"),
  student_race = list(sheet = 5, range = "A3:E4"),
  student_need = list(sheet = 5, range = "A9:F10"),
  community = list(sheet = 6, range = "A3:G17"),
  walk = list(sheet = 6, range = "A22:E25"),
  ypll = list(sheet = 7, range = "A3:D29"),
  drugs = list(sheet = 7, range = "A34:B51"),
  diabetes = list(sheet = 8, range = "A3:B17"),
  smoke_cws = list(sheet = 9, range = "A36:B50"),
  dental_cws = list(sheet = 9, range = "A88:B102")
)

sheets <- imap(sheet_info, function(sht, name) {
  read_excel(xl_path, sheet = sht$sheet, range = sht$range)
})
```

```{r}
sheets$proj_pop
```

```{r fig.height=2.7, fig.width=7}
proj_plot <- sheets$proj_pop %>%
  select(Age:`2040`) %>%
  filter(Age != "Total") %>%
  gather(key = year, value = value, -Age) %>%
  mutate(Age = as.factor(Age) %>% fct_inorder()) %>%
  mutate(type = ifelse(year > 2015, "future", "past")) %>%
  mutate(value = value %>% magrittr::divide_by(1000)) %>%
  ggplot(aes(x = year, y = value, fill = Age)) +
    geom_col(aes(alpha = type), position = "dodge", width = 0.8) +
    geom_text(aes(label = round(value)), fontface = "bold", family = "archivo", size = 3, vjust = 0, nudge_y = 1) +
    scale_fill_manual(values = pal5, guide = F) +
    scale_alpha_manual(values = c(future = 0.7, past = 0.95), guide = F) +
    scale_y_continuous(expand = expand_scale(mult = c(0, 0.08)), labels = NULL) +
    facet_wrap(~ Age, nrow = 1) +
    labs(x = NULL, y = "Population (thousands)", title = "Projected population by age group", subtitle = "Greater Waterbury, 2000-2040") +
    theme_din(base_family = "archivo", base_size = 12) +
    theme(axis.text.x = element_text(size = rel(0.85)), strip.text = element_text(face = "bold"))

proj_plot
```

```{r fig.height=4, fig.width=5}
text_pal <- pal[c(10, 8, 6, 4)] %>% colorspace::darken(amount = 0.4)
race_age_no_label <- sheets$age_race %>%
  filter(Age != "All ages") %>%
  select(Age, White, Black, Latino = Hispanic, `Other race`) %>%
  gather(key = Race, value = value, -Age) %>%
  mutate_at(vars(Age, Race), function(x) as.factor(x) %>% fct_inorder()) %>%
  ggplot() +
    geom_mosaic(aes(x = product(Race, Age), weight = value, fill = Race), offset = 0.005, alpha = 0.9, show.legend = F) +
    geom_point(aes(x = 0, y = 0, fill = Race), shape = 22, size = 0, color = "white") +
    geom_text(aes(x = 0, y = value, color = fct_rev(Race), label = Race), data = . %>% filter(Age == "Under 5"), position = position_fill(vjust = 0.5), hjust = 1.1, size = 3.2, fontface = "bold", family = "archivo") +
    scale_y_continuous(labels = NULL, expand = expand_scale(mult = c(0, 0.05))) +
    # scale_fill_manual(values = pal[c(4, 6, 8, 10)]) +
    scale_fill_manual(values = colorspace::qualitative_hcl(4, h = c(90, 232), c = 70, l = 55)) +
    scale_color_manual(values = colorspace::qualitative_hcl(4, h = c(232, 90), c = 70, l = 35), guide = F) +
    # guides(fill = guide_legend(override.aes = list(size = 7))) +
    # guides(fill = NULL, color = NULL) +
    theme_din(base_family = "archivo", base_size = 12) +
    # theme(legend.key = element_rect(color = "white", fill = "white"), axis.text = element_text(size = rel(0.7))) +
    theme(legend.position = "none", axis.text = element_text(size = rel(0.75))) +
    coord_cartesian(xlim = c(-0.12 / 1.1, 1.02 / 1.1)) +
    labs(x = NULL, y = NULL, title = "Population by age and race", subtitle = "Greater Waterbury, 2010")

ra_labels <- ggplot_build(race_age_no_label)$data[[1]] %>%
  select(age = x2__Age, value = .wt, xmin:ymax, label) %>%
  group_by(age) %>%
  mutate(share = round(value / sum(value), digits = 2)) %>%
  mutate(race = str_remove(label, "\\\n.+$") %>% as.factor() %>% fct_relevel("White", "Black", "Latino", "Other race") %>% fct_rev()) %>%
  select(-label) %>%
  rowwise() %>%
  mutate(x = mean(c(xmin, xmax)))

race_age_plot <- race_age_no_label +
  ggrepel::geom_text_repel(aes(x = x, y = share, group = race, label = scales::percent(share)), 
                           data = ra_labels, position = position_fill(vjust = 0.5), 
                           size = 2.8, color = "black", family = "archivo", fontface = "bold", 
                           direction = "y", force = 0.0005, box.padding = 0)
race_age_plot
```

```{r}
income_town <- get_acs(geography = "county subdivision", variable = c(median_income = "B19013_001"), state = "09", year = 2016) %>%
  town_names(NAME) %>%
  select(name = NAME, estimate) %>%
  filter(name %in% towns)
income_ct <- get_acs(geography = "state", variable = c(median_income = "B19013_001"), year = 2016) %>%
  filter(NAME == "Connecticut") %>%
  select(name = NAME, estimate)
hh_town <- get_acs(geography = "county subdivision", variable = c(households = "B11016_001"), state = "09", year = 2016) %>%
  town_names(NAME) %>%
  select(name = NAME, households = estimate) %>%
  filter(name %in% towns)


```

```{r fig.height=2.5, fig.width=3}
income_plot <- income_town %>%
  inner_join(hh_town, by = "name") %>%
  mutate(name = "Greater\nWaterbury") %>%
  group_by(name) %>%
  # summarise(estimate = Hmisc::wtd.quantile(estimate, households, probs = 0.5)) %>%
  summarise(estimate = weighted.mean(estimate, households) %>% round()) %>%
  bind_rows(income_town %>% filter(name == "Waterbury"), income_ct) %>%
  mutate(name = as.factor(name) %>% fct_relevel("Connecticut", "Greater\nWaterbury", "Waterbury")) %>%
  ggplot(aes(x = name, y = estimate)) +
    geom_col(fill = pal[8], width = 0.8, alpha = 0.9) +
    geom_text(aes(label = scales::dollar(estimate)), vjust = 0, nudge_y = 1000, fontface = "bold", family = "archivo", size = 3.2) +
    scale_y_continuous(expand = expand_scale(mult = c(0, 0.07)), labels = NULL) +
    theme_din(base_family = "archivo", base_size = 12) +
    labs(x = NULL, y = NULL, title = "Median household income", subtitle = "By location, 2016")

income_plot
```

```{r fig.height=5, fig.width=5, message=FALSE, warning=FALSE}
industry_plot <- sheets$industry %>%
  mutate(Industry = Industry %>% str_replace("and", "&") %>% str_replace("Government", "Govt") %>% str_replace("Administration", "Admin") %>% str_replace("Assistance", "Asst.")) %>%
  gather(key = year, value = value, -Industry) %>%
  mutate(year = as.integer(year)) %>%
  mutate(value = value / 1000) %>%
  mutate(l_lab = sprintf("%sk", round(value))) %>%
  mutate(r_lab = sprintf("%s: %s", Industry, l_lab)) %>%
  ggplot(aes(x = year, y = value, color = Industry, group = Industry)) +
    geom_segment(aes(x = x, xend = xmax, y = y, yend = y), data = tibble(x = 2002, xmax = 2015, y = seq(0, 20, by = 5) ), inherit.aes = F, color = "gray80", size = 0.4) +
    geom_point() +
    geom_smooth(method = loess, se = F, alpha = 0.9) +
    ggrepel::geom_text_repel(aes(label = l_lab), data = . %>% filter(year == min(year)), hjust = 1, nudge_x = -0.5, lineheight = 0.9, size = 3.2, fontface = "bold", family = "archivo", direction = "y", min.segment.length = 10, force = 0.5) +
    ggrepel::geom_text_repel(aes(label = r_lab), data = . %>% filter(year == max(year)), hjust = 0, nudge_x = 0.5, lineheight = 0.9, size = 3.2, fontface = "bold", family = "archivo", direction = "y", min.segment.length = 10, force = 0.5) +
    scale_color_manual(values = colorspace::qualitative_hcl(8, h = c(0, 232), c = 70, l = 55)) +
    # rcartocolor::scale_color_carto_d(palette = "Bold") +
    scale_y_continuous(limits = c(0, NA), labels = NULL) +
    scale_x_continuous(expand = expand_scale(mult = c(0.15, 0.95)), breaks = c(2002, 2015)) +
    theme_din(base_size = 12, base_family = "archivo", ygrid = F) +
    theme(legend.position = "none") +
    labs(x = NULL, y = NULL, title = "Employment in largest industries", subtitle = "Greater Waterbury employees, 2002-2015")

industry_plot
```

```{r fig.height=4.25, fig.width=5.5}
resource_plot <- sheets$resources %>%
  gather(key = measure, value = value, -Name) %>%
  mutate(value = round(value, digits = 2)) %>%
  mutate(Name = as.factor(Name) %>% 
           fct_inorder() %>% 
           fct_relevel("Waterbury", after = 1) %>%
           fct_recode(Black = "Black/Afr Amer", Latino = "Hispanic") %>%
           fct_relabel(function(x) ifelse(str_detect(x, "^\\d"), paste("Ages", x), x))) %>%
  mutate(region = Name %>% fct_other(keep = c("Connecticut", "Waterbury"), other_level = "Greater Waterbury")) %>%
  filter(Name != "Other") %>%
  mutate(type = Name %>% 
           fct_collapse("By location" = c("Connecticut", "Greater Waterbury", "Waterbury"), 
                        "By age" = c("Ages 18-34", "Ages 35-49", "Ages 50-64", "Ages 65+"), 
                        "By race" = c("White", "Black", "Latino"), 
                        "By income" = c("Under $30k", "$30-$100k", "$100k and up"))) %>%
  ggplot(aes(x = fct_rev(Name), y = value, fill = region)) +
    geom_col(position = "dodge", width = 0.85, alpha = 0.9) +
    geom_text(aes(label = value * 100), fontface = "bold", size = 2.8, family = "archivo", hjust = 1, color = "white", nudge_y = -0.005) +
    scale_fill_manual(values = c("gray30", "gray30", pal[8]), guide = F) +
    scale_y_continuous(labels = NULL, expand = expand_scale(mult = c(0, 0.1))) +
    coord_flip() +
    facet_grid(type ~ measure, scales = "free_y", space = "free", switch = "y") +
    theme_din(base_family = "archivo", base_size = 12, ygrid = F, xgrid = T) +
    theme(strip.placement = "outside", strip.text = element_text(face = "bold"), 
          panel.spacing.x = unit(0.5, "cm"), axis.text = element_text(size = rel(0.75))) +
    labs(x = NULL, y = "Percentage of adults", title = "Access to resources", subtitle = "By location and Greater Waterbury demographic groups, 2015")

resource_plot
```

regional 16: beacon falls, prospect *
regional 14: bethlehem, woodbury *
regional 12: bridgewater, roxbury, washington *
regional 6: goshen, morris, warren *
regional 15: middlebury, southbury *

```{r}
regionals <- c("06", 12, 14, 15, 16) %>% paste("Regional ", .)

student_race <- read_csv("http://data.ctdata.org/dataset/9572f54c-b1c3-4153-8ead-e5b16e678d90/resource/bf57c924-c677-44af-853c-63615f22c2bc/download/studentenrollmentbyraceethnicity2011-2018.csv") %>%
  filter(Year == "2017-2018", `Measure Type` == "Number") %>%
  select(district = District, race = `Race/Ethnicity`, value = Value) %>%
  mutate(district = district %>% str_remove("School District") %>% str_trim()) %>%
  filter(value > 0) %>% 
  filter(district %in% c(towns, regionals)) %>% 
  mutate(race = as.factor(race) %>% fct_recode(Black = "Black or African American", Latino = "Hispanic/Latino of any race") %>% fct_other(keep = c("White", "Black", "Latino", "Asian"), other_level = "Other race")) %>%
  group_by(race) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(value = value %>% magrittr::divide_by(1000) %>% floor() %>% as.integer()) %>%
  arrange(desc(value))

# student_race <- sheets$student_race %>%
#   gather(key = race, value = value) %>%
#   mutate(value = value %>% magrittr::divide_by(1000) %>% floor() %>% as.integer()) %>%
#   arrange(desc(value))

```

```{r fig.height=3, fig.width=3}
sr_vec <- student_race$value
names(sr_vec) <- student_race$race
student_race_plot <- waffle(sr_vec, rows = 5, colors = pal[c(7, 3, 4, 9, 6)], size = 1) + 
  theme_din(base_size = 12, base_family = "archivo", ygrid = F) +
  theme(legend.position = "bottom", legend.key.size = unit(5, "mm"), 
        axis.title = element_blank(), axis.text = element_blank(), 
        plot.margin = margin(2, 2, 2, 2, "pt"),
        legend.box.spacing = unit(6, "pt")) +
  guides(fill = guide_legend(byrow = T)) +
  labs(title = "Public school students by race", subtitle = "Greater Waterbury, 2017-2018", caption = "1 box = 1,000 students")

student_race_plot
```

```{r fig.height=2, fig.width=4}
wrap20 <- scales::wrap_format(15)

student_need <- read_csv("http://data.ctdata.org/dataset/8cad880f-4db0-4201-afa2-60a471fbc2fd/resource/ffec92b1-6412-40fa-9b05-81daa17ea69a/download/educationalneed2016-2017.csv") %>%
  filter(Year == "2016-2017", `Measure Type` == "Number") %>%
  select(district = District, need = `Indicator of Educational Need`, value = Value) %>%
  mutate(district = district %>% str_remove("School District") %>% str_trim()) %>%
  filter(value > 0) %>% 
  filter(district %in% c(towns, regionals)) %>%
  mutate(need = need %>% str_to_lower() %>% cap_first() %>% as.factor() %>% fct_recode("Free/reduced price meals" = "Eligible for free or reduced price lunch", "English-lang. learners" = "English language learner", "Special ed." = "Special education", total = "Total students evaluated")) %>%
  group_by(need) %>%
  summarise(value = sum(value)) %>%
  spread(key = need, value = value) %>%
  gather(key = need, value = value, -total) %>%
  mutate(share = round(value / total, digits = 2)) %>%
  mutate(share_not = 1 - share) %>%
  select(-total) %>%
  gather(key = isGrp, value = share, share, share_not) %>%
  group_by(isGrp) %>%
  mutate(need = fct_reorder(need, share, min)) %>%
  ungroup() %>%
  mutate(isGrp = as.factor(isGrp) %>% fct_relevel("share"))

student_need_plot <- ggplot(student_need, aes(x = fct_rev(need), y = share, fill = fct_rev(isGrp))) +
    geom_col(position = "fill", alpha = 0.9, width = 0.8) +
    geom_text(aes(label = share * 100), data = . %>% filter(isGrp == "share"), hjust = 1, size = 3.2, family = "archivo", fontface = "bold", nudge_y = -0.01, color = "white") +
    scale_fill_manual(values = c("share" = pal[9], "share_not" = "gray80"), guide = F) +
    scale_x_discrete(labels = wrap20) +
    scale_y_continuous(expand = expand_scale(mult = c(0, 0.05)), labels = NULL) +
    coord_flip() +
    theme_din(base_size = 12, base_family = "archivo", xgrid = T, ygrid = F) +
    labs(y = "Percentage of students", x = NULL, title = "Higher-needs public school students", subtitle = "Shares of Greater Waterbury students, 2016-2017")

student_need_plot
```


```{r fig.height=4.25, fig.width=5.5}
cohesion <- sheets$community %>% select(1, 3, 4, 7)
civic <- sheets$community %>% select(1, 2, 5, 6)
cohesion_plot <- cohesion %>%
  gather(key = measure, value = value, -Name) %>%
  mutate(value = round(value, digits = 2)) %>%
  mutate(Name = as.factor(Name) %>% 
           fct_inorder() %>% 
           fct_relevel("Waterbury", after = 1) %>%
           fct_recode(Black = "Black/Afr Amer", Latino = "Hispanic") %>%
           fct_relabel(function(x) ifelse(str_detect(x, "^\\d"), paste("Ages", x), x))) %>%
  mutate(region = Name %>% fct_other(keep = c("Connecticut", "Waterbury"), other_level = "Greater Waterbury")) %>%
  filter(Name != "Other") %>%
  mutate(measure = scales::wrap_format(20)(measure)) %>%
  mutate(type = Name %>% 
           fct_collapse("By location" = c("Connecticut", "Greater Waterbury", "Waterbury"), 
                        "By age" = c("Ages 18-34", "Ages 35-49", "Ages 50-64", "Ages 65+"), 
                        "By race" = c("White", "Black", "Latino"), 
                        "By income" = c("Under $30k", "$30-$100k", "$100k and up"))) %>%
  ggplot(aes(x = fct_rev(Name), y = value, fill = region)) +
    geom_col(position = "dodge", width = 0.85, alpha = 0.9) +
    geom_text(aes(label = value * 100), fontface = "bold", size = 2.8, family = "archivo", hjust = 1, color = "white", nudge_y = -0.01) +
    scale_fill_manual(values = c("gray30", "gray30", pal[8]), guide = F) +
    scale_y_continuous(labels = NULL, expand = expand_scale(mult = c(0, 0.1))) +
    coord_flip() +
    facet_grid(type ~ measure, scales = "free_y", space = "free", switch = "y") +
    theme_din(base_family = "archivo", base_size = 12, ygrid = F, xgrid = T) +
    theme(strip.placement = "outside", strip.text = element_text(face = "bold"), 
          panel.spacing.x = unit(0.5, "cm"), axis.text = element_text(size = rel(0.75))) +
    labs(x = NULL, y = "Percentage of adults", title = "Community cohesion", subtitle = "By location and Greater Waterbury demographic groups, 2015")

cohesion_plot
```

```{r, fig.height=4.25, fig.width=5.5}
civic_plot <- civic %>%
  gather(key = measure, value = value, -Name) %>%
  mutate(value = round(value, digits = 2)) %>%
  mutate(Name = as.factor(Name) %>% 
           fct_inorder() %>% 
           fct_relevel("Waterbury", after = 1) %>%
           fct_recode(Black = "Black/Afr Amer", Latino = "Hispanic") %>%
           fct_relabel(function(x) ifelse(str_detect(x, "^\\d"), paste("Ages", x), x))) %>%
  mutate(region = Name %>% fct_other(keep = c("Connecticut", "Waterbury"), other_level = "Greater Waterbury")) %>%
  filter(Name != "Other") %>%
  mutate(measure = scales::wrap_format(20)(measure)) %>%
  mutate(type = Name %>% 
           fct_collapse("By location" = c("Connecticut", "Greater Waterbury", "Waterbury"), 
                        "By age" = c("Ages 18-34", "Ages 35-49", "Ages 50-64", "Ages 65+"), 
                        "By race" = c("White", "Black", "Latino"), 
                        "By income" = c("Under $30k", "$30-$100k", "$100k and up"))) %>%
  ggplot(aes(x = fct_rev(Name), y = value, fill = region)) +
    geom_col(position = "dodge", width = 0.85, alpha = 0.9) +
    geom_text(aes(label = value * 100), fontface = "bold", size = 2.8, family = "archivo", hjust = 1, color = "white", nudge_y = -0.01) +
    scale_fill_manual(values = c("gray30", "gray30", pal[8]), guide = F) +
    scale_y_continuous(labels = NULL, expand = expand_scale(mult = c(0, 0.1))) +
    coord_flip() +
    facet_grid(type ~ measure, scales = "free_y", space = "free", switch = "y") +
    theme_din(base_family = "archivo", base_size = 12, ygrid = F, xgrid = T) +
    theme(strip.placement = "outside", strip.text = element_text(face = "bold"), 
          panel.spacing.x = unit(0.5, "cm"), axis.text = element_text(size = rel(0.75))) +
    labs(x = NULL, y = "Percentage of adults", title = "Civic well-being", subtitle = "By location and Greater Waterbury demographic groups, 2015")

civic_plot
```

```{r fig.height=2, fig.width=7}
walk_plot <- sheets$walk %>%
  gather(key = measure, value = value, -Name) %>%
  mutate(value = round(value, digits = 2)) %>%
  mutate(measure = measure %>% str_replace("other locations", "etc") %>% scales::wrap_format(30)()) %>%
  mutate(Name = Name %>% scales::wrap_format(10)() %>% as.factor() %>% fct_rev()) %>%
  ggplot(aes(x = Name, y = value, fill = Name)) +
    geom_col(width = 0.8, alpha = 0.9) +
    geom_text(aes(label = value * 100), fontface = "bold", size = 3.2, family = "archivo", hjust = 1, color = "white", nudge_y = -0.02) +
    scale_fill_manual(values = pal[c(6, 7, 8)], guide = F) +
    scale_y_continuous(labels = NULL, expand = expand_scale(mult = c(0, 0.1))) +
    coord_flip() +
    facet_wrap(~ measure, nrow = 1) +
    theme_din(base_size = 12, base_family = "archivo", xgrid = T, ygrid = F) +
    theme(strip.text = element_text(face = "bold")) +
    labs(x = NULL, y = NULL, title = "Walkability by location, 2015", subtitle = "Percentage of adults reporting walkability measures")

walk_plot
```

```{r fig.height=6, fig.width=4}
ypll_plot <- sheets$ypll %>%
  mutate(Type = as.factor(Type) %>% fct_inorder()) %>%
  gather(key = location, value = value, Waterbury, Connecticut) %>%
  rename(cause = `Cause of death`) %>%
  mutate(value = round(value)) %>%
  filter(!str_detect(cause, "All causes")) %>%
  # group_by(location) %>%
  mutate(cause = as.factor(cause) %>% fct_recode("Infant mortality" = "Infant Mortality (74.5 years/death)", "Chron. lower respir. disease" = "Chronic lower respiratory disease") %>% fct_reorder(value, max)) %>%
  arrange(Type, cause) %>%
  ggplot(aes(x = cause, y = value, color = location)) +
    geom_point(alpha = 0.7, size = 3) +
    geom_text(aes(label = location), data = . %>% filter(cause == "Infant mortality"), size = 3, family = "archivo", fontface = "bold", nudge_x = 0.5, vjust = 0, hjust = 1) +
    scale_color_manual(values = c("Waterbury" = pal[9], "Connecticut" = pal[6]), guide = F) +
    scale_y_continuous(labels = scales::comma) +
    scale_x_discrete(expand = expand_scale(add = c(0.5, 1))) +
    coord_flip() +
    facet_grid(Type ~ ., scales = "free_y", space = "free") +
    labs(x = NULL, y = "YPLL per 100k residents", title = "Years of potential life lost", subtitle = "By cause of death, 2008-2012") +
    theme_din(base_family = "archivo", base_size = 12, xgrid = T) +
    theme(strip.text = element_text(face = "bold"))

ypll_plot
```

```{r}
town_sf <- tigris::county_subdivisions(state = "09", cb = T, class = "sf") %>%
  filter(NAME %in% towns) %>%
  select(NAME, geometry)
```

```{r fig.height=3, fig.width=3}
drug_brks <- classInt::classIntervals(sheets$drugs$Count, 4, "jenks")$brk

drug_map <- town_sf %>%
  mutate(x = st_centroid(.) %>% st_coordinates() %>% .[, 1]) %>%
  mutate(y = st_centroid(.) %>% st_coordinates() %>% .[, 2]) %>%
  full_join(sheets$drugs, by = c("NAME" = "Town")) %>%
  arrange(desc(Count)) %>%
  ggplot() +
    geom_sf(color = "gray70", size = 0.4, fill = "gray95") +
    geom_point(aes(x = x, y = y, size = Count), color = pal[7], alpha = 0.8) +
    scale_x_continuous(breaks = NULL) +
    scale_y_continuous(breaks = NULL) +
    scale_size_area(breaks = drug_brks) +
    theme_din(base_size = 12, base_family = "archivo") +
    coord_sf(ndiscr = F) +
    labs(x = NULL, y = NULL, title = "Drug-related deaths", subtitle = "Greater Waterbury towns, 1/2012-6/2017")

drug_map
```

```{r fig.height=3.75, fig.width=3.5}
diabetes_plot <- sheets$diabetes %>%
  # gather(key = measure, value = value, -Name) %>%
  rename(value = Diabetes) %>%
  mutate(value = round(value, digits = 2)) %>%
  mutate(Name = as.factor(Name) %>% 
           fct_inorder() %>% 
           fct_relevel("Waterbury", after = 1) %>%
           fct_recode(Black = "Black/Afr Amer", Latino = "Hispanic") %>%
           fct_relabel(function(x) ifelse(str_detect(x, "^\\d"), paste("Ages", x), x))) %>%
  mutate(region = Name %>% fct_other(keep = c("Connecticut", "Waterbury"), other_level = "Greater Waterbury")) %>%
  filter(Name != "Other") %>%
  # mutate(measure = scales::wrap_format(20)(measure)) %>%
  mutate(type = Name %>% 
           fct_collapse("By location" = c("Connecticut", "Greater Waterbury", "Waterbury"), 
                        "By age" = c("Ages 18-34", "Ages 35-49", "Ages 50-64", "Ages 65+"), 
                        "By race" = c("White", "Black", "Latino"), 
                        "By income" = c("Under $30k", "$30-$100k", "$100k and up"))) %>%
  ggplot(aes(x = fct_rev(Name), y = value, fill = region)) +
    geom_col(position = "dodge", width = 0.85, alpha = 0.9) +
    geom_text(aes(label = value * 100), fontface = "bold", size = 2.8, family = "archivo", hjust = 1, color = "white", nudge_y = -0.005) +
    scale_fill_manual(values = c("gray30", "gray30", pal[8]), guide = F) +
    scale_y_continuous(labels = NULL, expand = expand_scale(mult = c(0, 0.1))) +
    coord_flip() +
    facet_grid(type ~ ., scales = "free_y", space = "free", switch = "y") +
    theme_din(base_family = "archivo", base_size = 12, ygrid = F, xgrid = T) +
    theme(strip.placement = "outside", strip.text = element_text(face = "bold"), 
          panel.spacing.x = unit(0.5, "cm"), axis.text = element_text(size = rel(0.75))) +
    labs(x = NULL, y = "Percentage of adults", title = "Diabetes rate", subtitle = "By location and Greater Waterbury\ndemographic groups, 2015")

diabetes_plot
```

```{r}
sheets$smoke_cws
```


```{r}
cdc <- read.socrata("https://chronicdata.cdc.gov/resource/csmm-fdhi.json?stateabbr=CT&cityname=Waterbury") %>%
  select(cityname, tractfips, data_value, geographiclevel, short_question_text, year) %>%
  filter(geographiclevel == "Census Tract") %>%
  mutate(data_value = as.numeric(data_value) / 100) %>%
  select(tract = tractfips, question = short_question_text, value = data_value, year)
```

```{r}
xwalk <- read_csv("../reference/ct_xwalk.csv") %>%
  select(tract = trct, town = ctycsubname) %>%
  mutate(town = str_remove(town, " town.+$")) %>%
  unique()
wby_tract <- xwalk %>% filter(town == "Waterbury") %>% pull(tract)
tract_sf <- tigris::tracts(state = "09", county = "09", cb = T, class = "sf") %>%
  filter(GEOID %in% wby_tract) %>%
  select(tract = GEOID, geometry)
```

```{r}
unique(cdc$question)
```


```{r fig.height=2.5, fig.width=3}
checkup_map <- cdc %>%
  filter(question == "Annual Checkup") %>%
  mutate(value = signif(value, digits = 2)) %>%
  mutate(brk = classInt::classIntervals(value, 5, "jenks")$brk %>% 
           cut(value, breaks = ., include.lowest = T) %>% 
           fct_relabel(brk_labels, "percent", mult_by = 100)) %>%
  full_join(tract_sf, by = "tract") %>%
  ggplot() +
    geom_sf(aes(fill = brk), color = "white", size = 0.2) +
    geom_sf(color = "gray60", size = 1, data = town_sf %>% filter(NAME == "Waterbury"), fill = "transparent") +
    scale_fill_brewer(palette = "YlGnBu") +
    scale_y_continuous(breaks = NULL) +
    scale_x_continuous(breaks = NULL) +
    theme_din(base_size = 12, base_family = "archivo") +
    coord_sf(ndiscr = F) +
    labs(fill = "Rate", title = "Received annual checkup", subtitle = "Waterbury adults by census tract, 2015") +
    theme(legend.text = element_text(size = rel(0.7)), legend.key.size = unit(5, "mm"))

checkup_map
```

```{r fig.height=2, fig.width=2.5}
smoking_map_piece <- cdc %>%
  filter(question == "Current Smoking") %>%
  mutate(value = signif(value, digits = 2)) %>%
  mutate(brk = classInt::classIntervals(value, 6, "jenks")$brk %>% 
           unique() %>%
           cut(value, breaks = ., include.lowest = T) %>% 
           fct_relabel(brk_labels, "percent", mult_by = 100)) %>%
  full_join(tract_sf, by = "tract") %>%
  ggplot() +
    geom_sf(aes(fill = brk), color = "white", size = 0.2) +
    geom_sf(color = "gray60", size = 1, data = town_sf %>% filter(NAME == "Waterbury"), fill = "transparent") +
    scale_fill_brewer(palette = "YlGnBu", drop = F) +
    scale_y_continuous(breaks = NULL) +
    scale_x_continuous(breaks = NULL) +
    theme_din(base_size = 12, base_family = "archivo") +
    coord_sf(ndiscr = F) +
    labs(fill = "Rate", title = "Current smoking", subtitle = "Waterbury adults by census tract, 2014") +
    theme(legend.text = element_text(size = rel(0.7)), legend.key.size = unit(4, "mm"))

smoking_map_piece
```

```{r fig.height=2, fig.width=2.5}
dental_map_piece <- cdc %>%
  filter(question == "Dental Visit") %>%
  mutate(value = signif(value, digits = 2)) %>%
  mutate(brk = classInt::classIntervals(value, 5, "jenks")$brk %>% 
           cut(value, breaks = ., include.lowest = T) %>% 
           fct_relabel(brk_labels, "percent", mult_by = 100)) %>%
  full_join(tract_sf, by = "tract") %>%
  ggplot() +
    geom_sf(aes(fill = brk), color = "white", size = 0.2) +
    geom_sf(color = "gray60", size = 1, data = town_sf %>% filter(NAME == "Waterbury"), fill = "transparent") +
    scale_fill_brewer(palette = "YlGnBu") +
    scale_y_continuous(breaks = NULL) +
    scale_x_continuous(breaks = NULL) +
    theme_din(base_size = 12, base_family = "archivo") +
    coord_sf(ndiscr = F) +
    labs(fill = "Rate", title = "Dental visit in past year", subtitle = "Waterbury adults by census tract, 2014") +
    theme(legend.text = element_text(size = rel(0.7)), legend.key.size = unit(4, "mm"))

dental_map_piece
```

```{r fig.height=3.75, fig.width=2.5}
smoke_bars <- sheets$smoke_cws %>%
  rename(value = `Smoking rate`) %>%
  mutate(value = round(value, digits = 2)) %>%
  mutate(Name = as.factor(Name) %>% 
           fct_inorder() %>% 
           fct_relevel("Waterbury", after = 1) %>%
           fct_recode(Black = "Black/Afr Amer", Latino = "Hispanic") %>%
           fct_relabel(function(x) ifelse(str_detect(x, "^\\d"), paste("Ages", x), x))) %>%
  mutate(region = Name %>% fct_other(keep = c("Connecticut", "Waterbury"), other_level = "Greater Waterbury")) %>%
  filter(Name != "Other") %>%
  # mutate(measure = scales::wrap_format(20)(measure)) %>%
  mutate(type = Name %>% 
           fct_collapse("By location" = c("Connecticut", "Greater Waterbury", "Waterbury"), 
                        "By age" = c("Ages 18-34", "Ages 35-49", "Ages 50-64", "Ages 65+"), 
                        "By race" = c("White", "Black", "Latino"), 
                        "By income" = c("Under $30k", "$30-$100k", "$100k and up"))) %>%
  ggplot(aes(x = fct_rev(Name), y = value, fill = region)) +
    geom_col(position = "dodge", width = 0.85, alpha = 0.9) +
    geom_text(aes(label = value * 100), fontface = "bold", size = 2.8, family = "archivo", hjust = 1, color = "white", nudge_y = -0.003) +
    scale_fill_manual(values = c("gray30", "gray30", pal[8]), guide = F) +
    scale_y_continuous(labels = NULL, expand = expand_scale(mult = c(0, 0.1))) +
    coord_flip() +
    facet_grid(type ~ ., scales = "free_y", space = "free", switch = "y") +
    theme_din(base_family = "archivo", base_size = 12, ygrid = F, xgrid = T) +
    theme(strip.placement = "outside", strip.text = element_text(face = "bold"), 
          panel.spacing.x = unit(0.5, "cm"), axis.text = element_text(size = rel(0.75))) +
    labs(x = NULL, y = "Percentage of adults", title = "Current smoking rate", subtitle = "By location and Greater Waterbury\ndemographic groups, 2015")
```

```{r fig.height=3.75, fig.width=2.5}
dental_bars <- sheets$dental_cws %>%
  rename(value = `Dental visit`) %>%
  mutate(value = round(value, digits = 2)) %>%
  mutate(Name = as.factor(Name) %>% 
           fct_inorder() %>% 
           fct_relevel("Waterbury", after = 1) %>%
           fct_recode(Black = "Black/Afr Amer", Latino = "Hispanic") %>%
           fct_relabel(function(x) ifelse(str_detect(x, "^\\d"), paste("Ages", x), x))) %>%
  mutate(region = Name %>% fct_other(keep = c("Connecticut", "Waterbury"), other_level = "Greater Waterbury")) %>%
  filter(Name != "Other") %>%
  # mutate(measure = scales::wrap_format(20)(measure)) %>%
  mutate(type = Name %>% 
           fct_collapse("By location" = c("Connecticut", "Greater Waterbury", "Waterbury"), 
                        "By age" = c("Ages 18-34", "Ages 35-49", "Ages 50-64", "Ages 65+"), 
                        "By race" = c("White", "Black", "Latino"), 
                        "By income" = c("Under $30k", "$30-$100k", "$100k and up"))) %>%
  ggplot(aes(x = fct_rev(Name), y = value, fill = region)) +
    geom_col(position = "dodge", width = 0.85, alpha = 0.9) +
    geom_text(aes(label = value * 100), fontface = "bold", size = 2.8, family = "archivo", hjust = 1, color = "white", nudge_y = -0.01) +
    scale_fill_manual(values = c("gray30", "gray30", pal[8]), guide = F) +
    scale_y_continuous(labels = NULL, expand = expand_scale(mult = c(0, 0.1))) +
    coord_flip() +
    facet_grid(type ~ ., scales = "free_y", space = "free", switch = "y") +
    theme_din(base_family = "archivo", base_size = 12, ygrid = F, xgrid = T) +
    theme(strip.placement = "outside", strip.text = element_text(face = "bold"), 
          panel.spacing.x = unit(0.5, "cm"), axis.text = element_text(size = rel(0.75))) +
    labs(x = NULL, y = "Percentage of adults", title = "Dental visit in past year", subtitle = "By location and Greater Waterbury\ndemographic groups, 2015")
```

```{r}
# cowplot::plot_grid(dental_bars + ggtitle(NULL), dental_map, nrow = 1, rel_widths = c(1, 0.8))
```

```{r fig.height=4.5, fig.width=6.5}
health_bars <- bind_rows(
  sheets$smoke_cws %>% rename(value = `Smoking rate`) %>% mutate(measure = "Current smoking"),
  sheets$dental_cws %>% rename(value = `Dental visit`) %>% mutate(measure = "Dental visit in past year")
) %>%
  mutate(value = round(value, digits = 2)) %>%
  mutate(Name = as.factor(Name) %>% 
           fct_inorder() %>% 
           fct_relevel("Waterbury", after = 1) %>%
           fct_recode(Black = "Black/Afr Amer", Latino = "Hispanic") %>%
           fct_relabel(function(x) ifelse(str_detect(x, "^\\d"), paste("Ages", x), x))) %>%
  mutate(region = Name %>% fct_other(keep = c("Connecticut", "Waterbury"), other_level = "Greater Waterbury")) %>%
  filter(Name != "Other") %>%
  # mutate(measure = scales::wrap_format(20)(measure)) %>%
  mutate(type = Name %>% 
           fct_collapse("By location" = c("Connecticut", "Greater Waterbury", "Waterbury"), 
                        "By age" = c("Ages 18-34", "Ages 35-49", "Ages 50-64", "Ages 65+"), 
                        "By race" = c("White", "Black", "Latino"), 
                        "By income" = c("Under $30k", "$30-$100k", "$100k and up"))) %>%
  ggplot(aes(x = fct_rev(Name), y = value, fill = region)) +
    geom_col(position = "dodge", width = 0.85, alpha = 0.9) +
    geom_text(aes(label = value * 100), fontface = "bold", size = 2.8, family = "archivo", hjust = 1, color = "white", nudge_y = -0.01) +
    scale_fill_manual(values = c("gray30", "gray30", pal[8]), guide = F) +
    scale_y_continuous(labels = NULL, expand = expand_scale(mult = c(0, 0.1))) +
    coord_flip() +
    facet_grid(type ~ measure, scales = "free", space = "free_y", switch = "y") +
    theme_din(base_family = "archivo", base_size = 12, ygrid = F, xgrid = T) +
    theme(strip.placement = "outside", strip.text = element_text(face = "bold"), 
          panel.spacing.x = unit(0.5, "cm"), axis.text = element_text(size = rel(0.75))) +
    labs(x = NULL, y = "Percentage of adults", title = "Health risk factors", subtitle = "By location and Greater Waterbury demographic groups, 2015")

health_bars
```

```{r fig.height=3, fig.width=6.5}
health_maps <- cowplot::plot_grid(
  smoking_map_piece + theme(plot.title = element_text(size = rel(0.9)), plot.subtitle = element_text(size = rel(0.8))),
  dental_map_piece + theme(plot.title = element_text(size = rel(0.9)), plot.subtitle = element_text(size = rel(0.8)))
)
health_maps
```

```{r fig.height=7.5, fig.width=7}
health_risk_plot <- cowplot::plot_grid(health_bars, health_maps, ncol = 1, rel_heights = c(3.75, 2), align = "v", axis = "l")
health_risk_plot
```

```{r}
region_tract <- xwalk %>% filter(town %in% towns) %>% pull(tract)
reg_tract_sf <- tigris::tracts(state = "09", cb = T, class = "sf") %>%
  filter(GEOID %in% region_tract) %>%
  select(tract = GEOID, geometry)
```

```{r}
tract_xwalk <- read_csv("../reference/ct_xwalk.csv") %>%
  select(tract = trct, town = ctycsubname) %>%
  unique() %>%
  mutate(town = str_remove(town, " town .+$")) %>%
  filter(town %in% towns)
x <- c(total = 1, white = 3, black = 4, latino = 12)
race_trct <- structure(str_pad(x, width = 3, side = "left", pad = "0") %>% sprintf("B03002_%s", .), names = names(x)) %>%
  get_acs(geography = "tract", variables = ., year = 2016, state = "09") %>%
  select(tract = GEOID, race = variable, estimate) %>%
  filter(tract %in% tract_xwalk$tract)
```

```{r fig.height=3.5, fig.width=4}
race_map <- race_trct %>%
  calc_shares(tract, group = race, denom = "total") %>%
  filter(race == "white") %>%
  mutate(nonwhite = round(1 - share, digits = 2)) %>%
  select(tract, nonwhite) %>%
  mutate(brk = classInt::classIntervals(nonwhite, n = 7, style = "jenks")$brk %>% cut(nonwhite, breaks = ., include.lowest = T)) %>%
  mutate(brk = fct_relabel(brk, function(x) brk_labels(x, "percent", mult_by = 100))) %>%
  full_join(reg_tract_sf, by = "tract") %>%
  ggplot() +
    geom_sf(aes(fill = brk), size = 0.1, color = "white") +
    geom_sf(data = town_sf, size = 0.3, color = "gray40", fill = "transparent") +
    scale_fill_brewer(palette = "YlGnBu") +
    theme_din(base_size = 12) +
    coord_sf(ndiscr = F) +
    labs(fill = "Share", title = "Non-white population", subtitle = "Share by census tract, Greater Waterbury, 2016")

race_map
```














```{r}
ls()
ls(pattern = "_(map|plot)$")
```

```{r}
list(
    proj_plot = list(h = 2.7, w = 7),
    race_age_plot = list(h = 4, w = 5),
    income_plot = list(h = 2.5, w = 3),
    industry_plot = list(h = 5, w = 5),
    resource_plot = list(h = 4.25, w = 5.5),
    student_race_plot = list(h = 3, w = 3),
    student_need_plot = list(h = 2, w = 4),
    cohesion_plot = list(h = 4.25, w = 5.5),
    civic_plot = list(h = 4.25, w = 5.5),
    walk_plot = list(h = 2, w = 7),
    ypll_plot = list(h = 6, w = 4),
    drug_map = list(h = 3, w = 3),
    diabetes_plot = list(h = 3.75, w = 3.5),
    checkup_map = list(h = 2.5, w = 3),
    health_risk_plot = list(h = 7.5, w = 7),
    race_map = list(h = 3.5, w = 4)
) %>%
  iwalk(function(obj, name) {
    ggsave(sprintf("plots/%s.png", name), get(name), width = obj$w, height = obj$h, dpi = 600)
    ggsave(sprintf("plots/svg/%s.svg", name), get(name), width = obj$w, height = obj$h)
  })
```

